package PassMan;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author WANDE
 */
public class CreateAccount extends javax.swing.JFrame {
	private String key = "tisisthe16bitkey";

	/**
	 * Creates new form PassManMain
	 */
	public CreateAccount() {
		initComponents();
	}

	/**
	 * This method is called from within the
	 * constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The
	 * content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameArea = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createAcctbtn = new javax.swing.JButton();
        infoArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newUsnArea = new javax.swing.JTextField();
        newPass = new javax.swing.JPasswordField();
        newPassConfirm = new javax.swing.JPasswordField();
        createAcctNotif = new javax.swing.JLabel();
        cancelNewAcct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account - PassMan");
        setBackground(new java.awt.Color(0, 102, 204));
        setResizable(false);

        nameArea.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        nameArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameArea.setText("PassMan: Encrypted Password Manager v1.00.01");
        nameArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        loginPanel.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        createAcctbtn.setForeground(new java.awt.Color(0, 153, 0));
        createAcctbtn.setText("Create Account");
        createAcctbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAcctbtnActionPerformed(evt);
            }
        });

        infoArea.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Confirm Password");

        newPass.setToolTipText("Enter your password");

        newPassConfirm.setToolTipText("Repeat the password from above");

        createAcctNotif.setForeground(new java.awt.Color(255, 0, 51));
        createAcctNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cancelNewAcct.setForeground(new java.awt.Color(255, 51, 51));
        cancelNewAcct.setText("Cancel");
        cancelNewAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewAcctActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAcctNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cancelNewAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(createAcctbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(newPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(loginPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(213, 213, 213))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(newPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(newUsnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(1, 1, 1))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(infoArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAcctNotif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUsnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelNewAcct)
                    .addComponent(createAcctbtn))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelNewAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewAcctActionPerformed
        dispose();
        PassManMain newPassMan = new PassManMain();
        newPassMan.setVisible(true);
    }//GEN-LAST:event_cancelNewAcctActionPerformed

    private void createAcctbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAcctbtnActionPerformed
        String encPas = null;
        if (newUsnArea.getText().isEmpty() || newPass.getPassword().length < 1
            || newPassConfirm.getPassword().length < 1 ) {
            createAcctNotif.setText("All fields are required");
        } else {
            String newUsername = newUsnArea.getText();
            char[] newPassword = newPass.getPassword();
            char[] confirmNewPass = newPassConfirm.getPassword();

            if(!Arrays.equals(newPassword, confirmNewPass)){
                createAcctNotif.setText("Passwords don't match");
            }else{
                String stringPass = new String(newPassword);
                Crypt encryptPass = new Crypt(key);
                try {
                    encPas = encryptPass.encrypt(stringPass);
                } catch (Exception ex) {
                    createAcctNotif.setText("Unable to encrypt password");
                    //Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
                String filePath = newUsername + ".psm";
                FileWriter fileWriter = null;
                try {
                    fileWriter = new FileWriter(filePath, true);
                } catch (IOException ex) {
                    createAcctNotif.setText("Unable to create account file");
                    //Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                try {
                    bufferedWriter.write(encPas);
                    bufferedWriter.newLine();
                    bufferedWriter.close();
                    createAcctNotif.setText("Account created successfully");
                } catch (IOException ex) {
                    createAcctNotif.setText("Unable to write paswword to file");
                    //Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
                }

                newUsnArea.setText("");
                newPass.setText("");
                newPassConfirm.setText("");
            }
        }
    }//GEN-LAST:event_createAcctbtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreateAccount().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNewAcct;
    private javax.swing.JLabel createAcctNotif;
    private javax.swing.JButton createAcctbtn;
    private javax.swing.JLabel infoArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nameArea;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField newPassConfirm;
    private javax.swing.JTextField newUsnArea;
    // End of variables declaration//GEN-END:variables
}
